name: deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'habibutsu/gdal-boots' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Package and upload
        run: |
          pip install twine wheel
          python setup.py bdist_wheel
          twine upload \
            --verbose \
            --repository-url ${{ secrets.PYPI_URL }} \
            -u ${{ secrets.PYPI_USER }} \
            -p ${{ secrets.PYPI_PASSWORD }} \
            dist/*
