name: deploy

on:
  push:
    branches:
      - dev
  release:
    types: [ released ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
          apt-get update
          apt-get install -y --no-install-recommends gdal-bin libgdal-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Check isort
        run: isort -c .
#      - name: Lint with flake8
#        run: flake8 .
      - name: Test with pytest
        run: pytest --cov=gdal_boots

#      - name: Package and upload
#        env:
#          PACKAGE_VERSION: ${{ github.event.release.tag_name }}
#          TWINE_USERNAME: __token__
#          TWINE_PASSWORD: ${{ secrets.PYPI_APIKEY }}
#        run: |
#          pip install twine wheel
#          python setup.py sdist bdist_wheel
#          twine upload dist/*
