#name: deploy
#
#on:
#  push:
#    branches:
#      - master
#      - main
#  pull_request:
#    branches:
#      - master
#      - main
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v2
#
#      - name: Set up python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.9
#
#      - name: Install dependencies
#        run: |
#          sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable
#          sudo apt-get update
#          sudo apt-get install -y --no-install-recommends \
#            software-properties-common g++ gdal-bin libgdal-dev
#          python -m pip install --upgrade pip
#          pip install numpy
#          pip install -r requirements.txt
#          pip install -r requirements-dev.txt
#
#      - name: Check isort
#        run: isort -c .
#
##      - name: Lint with flake8
##        run: flake8 .
#
#      - name: Test with pytest
#        run: pytest --cov=gdal_boots
#
#  release:
#    runs-on: ubuntu-latest
#    needs:
#      - test
#    if: ${{ github.event_name == 'push' }}
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v2
#
#      - name: Set up python
#        uses: actions/setup-python@v2
#        with:
#          python-version: 3.9
#
#      - name: Package and upload
#        run: |
#          pip install twine wheel
#          python setup.py sdist bdist_wheel
#          twine upload \
#            --verbose \
#            --repository-url ${{ secrets.PYPI_URL }} \
#            -u ${{ secrets.PYPI_USER }} \
#            -p ${{ secrets.PYPI_PASSWORD }} \
#            dist/*
